import React, { useEffect } from 'react';
import { IoArrowUpCircleOutline } from "react-icons/io5";

export default function Membership() {

  useEffect(() => {
    scrollToTop();
}, [])

const scrollToTop = () => {
    window.scrollTo({
        top: 0,
        behavior: "smooth"
    });
};

  return (
    <div>
        <div className='container' style={{ marginTop: "6%" }}>
            <p style={{ fontSize: '3em', fontWeight: 500, color: "#DC143C", }}>Corporate Membership</p>
            <p className='text-start' style={{ fontSize: '1.2em', fontWeight: 600, color: "#000", }}>Eligibility Criteria :</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>The Applicant Company should be a private or public limited co.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>The Company shall be allowed to change its nomination in the event of the Nominee being transferred from Jaipur or on his retirement or on termination / resignation from the Company's Board / Services or upon his death or for any other valid reasons to the satisfaction of the club President & Secretary. However, no request for any changes for more than once in a year (viz in 365 days period) shall be entertained by the Club unless for reasons beyond one's control and whether to entertain the request or not is at the discretion of the Club's officials.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>The Club's Executive Committee and / or designated Committee shall review and give its clearance to the Company's Nominee initially proposed and / or subsequently proposed upon change before permitting the Nominees due availment of Clubs facilities. Further, the Committee shall have an unquestionable right to reject the Nomination proposed by the Company, which shall be duly conveyed not later than 45 days of its receipt by the Club Office.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>Membership under the Corporate Category shall be open round the year and members made under this category shall be over and above the ceiling fixed for Ordinary and Life Membership.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>The Corporate Membership Fee for time being shall be as per enclosed letter.) The Corporate Member shall not be liable to monthly fee but only liable to activity fee as charged in all other cases.The Executive Committee is empowered to review and raise the fee from time to time as also for temporarily suspending new membership under the criteria.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>The Corporate Member shall not be liable to monthly fee but only liable to activity fee as charged in all other cases.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>The Executive Committee is empowered to review and raise the fee from time to time as also for temporarily suspending new membership under the criteria.</p>
            <p className='text-start' style={{ fontSize: '1.2em', fontWeight: 600, color: "#000", }}>POST MEMBERSHIP COMPLIANCES :</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>The intention being to provide facilities to Operative and Functional Companies, the Companies shall be required to furnish every three years within following 8 months from the close of the third financial year, the following document voluntarily :</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>(a) Audited Balance Sheets with Auditors and Directors Report for preceding three years.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>(b) Evidences of filing of Returns of Incomes for preceding three years. </p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>(c) List of Directors with complete addresses.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>(d) Change of Regd. Office Address of the Company.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>The Club's Executive Committee and / or designated Committee shall review and give its clearance to the Company's Nominee initially proposed and / or subsequently proposed upon change before permitting the Nominees due availment of Clubs facilities. Further, the Committee shall have an unquestionable right to reject the Nomination proposed by the Company, which shall be duly conveyed not later than 45 days of its receipt by the Club Office.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>(i)The Club's Executive Committee shall have a right to suspend initially the right of use of club's facilities for 2 years by the Nominees and later to terminate / de-register the Club's membership in the following eventualities:</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>(a) The Company seizing to be commercially Operational or discontinuing its activities for over 2 years.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>(b) The Nominee and/or the Company being convicted of any Criminal Offence.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>(c) In the event of any indiscipline or breach of decorum by the Nominee.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>(ii) In the event of the Company's name being struck off under the Provisions of the Companies Act or winding up proceedings initiated, the Club Executive Committee shall have a right to cancel and terminate Company's Membership with immediate effect by giving a Notice to the Company.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>(iii) The Notice containing information of temporary suspension and / or termination/cancellation of Membership shall be communicated by Regd. Notice to the last intimated Regd. Office Address of the Company.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>All Applications should be filed with Requisite Membership Fees which shall be payable by Alc Payee Bankers Cheque / Draft, payable at Jaipur.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>All Applications submitted shall be registered chronologically in a register.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>The acceptance of the Application and deposit of admission Fee does not confer any right of membership to the applicant. It only means that his / her application shall be duly considered by the Executive Committee of the Club for Membership in due course of time.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>Application Form at any stage of processing can be rejected without assigning any reason thereto which shall not be challengeable in the court of Law.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>All applications shall be disposed off favourably or unfavourably within 60 Days of end of the month of its receipts. In the event of rejection, complete fees deposited with the application shall be refunded by an A/c Payee Cheque drawn in favour of the Company and which shall be sent along with rejection advice from the Club's office to the Registered Office Address of the Company conveyed in the Form.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>Any application once turned down unfavourably, the applicant shall not be eligible to reapply within the following 12 months from the end of the month in which the application is rejected.The Rejected applicant shall have no right to challenge the decision of the Executive Committee at any forum for reconsideration.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>Read the Form carefully, fill it properly. Incomplete form shall be rejected outrightly</p>
            <p className='text-start' style={{ fontSize: '1.2em', fontWeight: 600, color: "#000", }}>Individual Membership</p>
            <p className='text-start' style={{ fontSize: '1.2em', fontWeight: 600, color: "#000", }}>Eligibility Criteria :</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>The Applicant Company should be a private or public limited co.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>The Company shall be allowed to change its nomination in the event of the Nominee being transferred from Jaipur or on his retirement or on termination / resignation from the Company's Board / Services or upon his death or for any other valid reasons to the satisfaction of the club President & Secretary. However, no request for any changes for more than once in a year (viz in 365 days period) shall be entertained by the Club unless for reasons beyond one's control and whether to entertain the request or not is at the discretion of the Club's officials.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>The Club's Executive Committee and / or designated Committee shall review and give its clearance to the Company's Nominee initially proposed and / or subsequently proposed upon change before permitting the Nominees due availment of Clubs facilities. Further, the Committee shall have an unquestionable right to reject the Nomination proposed by the Company, which shall be duly conveyed not later than 45 days of its receipt by the Club Office.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>Membership under the Corporate Category shall be open round the year and members made under this category shall be over and above the ceiling fixed for Ordinary and Life Membership.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>The Corporate Membership Fee for time being shall be as per enclosed letter.) The Corporate Member shall not be liable to monthly fee but only liable to activity fee as charged in all other cases.The Executive Committee is empowered to review and raise the fee from time to time as also for temporarily suspending new membership under the criteria.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>The Corporate Member shall not be liable to monthly fee but only liable to activity fee as charged in all other cases.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>The Executive Committee is empowered to review and raise the fee from time to time as also for temporarily suspending new membership under the criteria.</p>
            <p className='text-start' style={{ fontSize: '1.2em', fontWeight: 600, color: "#000", }}>POST MEMBERSHIP COMPLIANCES :</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>The intention being to provide facilities to Operative and Functional Companies, the Companies shall be required to furnish every three years within following 8 months from the close of the third financial year, the following document voluntarily :</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>(a) Audited Balance Sheets with Auditors and Directors Report for preceding three years.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>(b) Evidences of filing of Returns of Incomes for preceding three years. </p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>(c) List of Directors with complete addresses.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>(d) Change of Regd. Office Address of the Company.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>The Club's Executive Committee and / or designated Committee shall review and give its clearance to the Company's Nominee initially proposed and / or subsequently proposed upon change before permitting the Nominees due availment of Clubs facilities. Further, the Committee shall have an unquestionable right to reject the Nomination proposed by the Company, which shall be duly conveyed not later than 45 days of its receipt by the Club Office.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>(i)The Club's Executive Committee shall have a right to suspend initially the right of use of club's facilities for 2 years by the Nominees and later to terminate / de-register the Club's membership in the following eventualities: </p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>(a) The Company seizing to be commercially Operational or discontinuing its activities for over 2 years. </p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>(b) The Nominee and/or the Company being convicted of any Criminal Offence.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>(c) In the event of any indiscipline or breach of decorum by the Nominee.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>(ii) In the event of the Company's name being struck off under the Provisions of the Companies Act or winding up proceedings initiated, the Club Executive Committee shall have a right to cancel and terminate Company's Membership with immediate effect by giving a Notice to the Company.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>(iii) The Notice containing information of temporary suspension and / or termination/cancellation of Membership shall be communicated by Regd. Notice to the last intimated Regd. Office Address of the Company.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>All Applications should be filed with Requisite Membership Fees which shall be payable by Alc Payee Bankers Cheque / Draft, payable at Jaipur.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>All Applications submitted shall be registered chronologically in a register.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>The acceptance of the Application and deposit of admission Fee does not confer any right of membership to the applicant. It only means that his / her application shall be duly considered by the Executive Committee of the Club for Membership in due course of time.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>Application Form at any stage of processing can be rejected without assigning any reason thereto which shall not be challengeable in the court of Law.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>All applications shall be disposed off favourably or unfavourably within 60 Days of end of the month of its receipts. In the event of rejection, complete fees deposited with the application shall be refunded by an A/c Payee Cheque drawn in favour of the Company and which shall be sent along with rejection advice from the Club's office to the Registered Office Address of the Company conveyed in the Form.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>Any application once turned down unfavourably, the applicant shall not be eligible to reapply within the following 12 months from the end of the month in which the application is rejected.The Rejected applicant shall have no right to challenge the decision of the Executive Committee at any forum for reconsideration.</p>
            <p className='text-start' style={{ fontSize: '1em', fontWeight: 400, color: "#000", }}>Read the Form carefully, fill it properly. Incomplete form shall be rejected outrightly</p>
        </div>
        <div className="scroll-to-top-button rounded-2" onClick={scrollToTop} style={{ width: 40, height: 40, backgroundColor: "#ff68f0", color: "#fff", alignItems: "center", justifyContent: "center", display: "flex", }}><IoArrowUpCircleOutline style={{ fontSize: 30 }} /></div>
    </div>
  )
}
